name: blog_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_sizer: ^1.0.5
  swipeable_page_route: ^0.4.2
  flutter_native_splash: ^2.4.0
  fpdart: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"


flutter_native_splash:
  color: "#000000"
  background_image: "assets/images/slplash.png"
